language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && R CMD INSTALL $PKG_TARBALL && source shim_package.sh && Rscript -e 'covr::codecov()'
